### ISSUE TITLE
DashboardJSON: cannot get terraform setup: cannot unmarshal datadog credentials as JSON: invalid character 'f' after top-level value

### ISSUE THREAD

**Issue by emily-zall** [crossplane-contrib/provider-jet-datadog#20]
### What happened?
My DashboardJSON is not Ready or Synced. When I describe the resource I get `Warning  CannotConnectToProvider  16s (x2 over 16s)   managed/dashboard.datadog.jet.crossplane.io/v1alpha1, kind=dashboardjson  cannot get terraform setup: cannot unmarshal datadog credentials as JSON: invalid character 'f' after top-level value`. If my secret format is wrong, what should it be?

```
emilyzall@Emilys-MBP config % kubectl get dashboardJSON
NAME                      READY   SYNCED   EXTERNAL-NAME   AGE
datadog-dashboard-fvbjl           False                    33m
```

### How can we reproduce it?
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-jet-datadog
spec:
  package: crossplane/provider-jet-datadog:v0.2.0
---
# https://github.com/crossplane-contrib/provider-jet-datadog/blob/main/examples/providerconfig/providerconfig.yaml
apiVersion: datadog.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: datadog
      namespace: test
      key: dd-api-key
```
The sanitized secret format looks like: 
```
  {
    "apiVersion": "v1",
    "data": {
        "dd-api-key": "FAKEVALUE,
        "dd-app-key": "FAKEVALUE"
    },
    "kind": "Secret",
    "metadata": {
        "creationTimestamp": "2023-06-05T15:06:12Z",
        "name": "datadog",
        "namespace": "test",
        "ownerReferences": [
            {
                "apiVersion": "kubernetes-client.io/v1",
                "controller": true,
                "kind": "ExternalSecret",
                "name": "datadog",
                "uid": "fake"
            }
        ],
        "resourceVersion": "32136291",
        "uid": "fake"
    },
    "type": "Opaque"
}
```

### What environment did it happen in?
Crossplane version: v1.12.1
Provider version: v0.2.0
OS: Mac Monterey 12.6.6
